"""
Analyze axis mapping verification data.

It reads CSV files generated by pc_axis_mapping_verify.py and writes:
- data/axis_mapping_summary.csv
- data/axis_mapping_report.md

Run on the computer after completing the physical verification sequence.
"""

from pathlib import Path
import csv
import math
import statistics


BASE_DIR = Path(__file__).resolve().parents[2]
DATA_DIR = BASE_DIR / "data" / "calibration" / "axis_mapping"
OUT_SUMMARY = BASE_DIR / "data" / "axis_mapping_summary.csv"
OUT_REPORT = BASE_DIR / "docs" / "axis_mapping_report.md"

STATIC_POSES = [
    "static_pos_x_up",
    "static_neg_x_up",
    "static_pos_y_up",
    "static_neg_y_up",
    "static_pos_z_up",
    "static_neg_z_up",
]

ROTATION_POSES = [
    "rotate_positive_roll_x",
    "rotate_positive_pitch_y",
    "rotate_positive_yaw_z",
]

HEADING_POSES = [
    "heading_x_forward",
    "heading_y_forward",
    "heading_neg_x_forward",
    "heading_neg_y_forward",
]


def read_csv(path):
    header = None
    rows = []
    with path.open("r", encoding="utf-8", newline="") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if line.startswith("t_ms,"):
                header = line.split(",")
                continue
            if header:
                parts = line.split(",")
                if len(parts) == len(header):
                    rows.append({k: v for k, v in zip(header, parts)})
    return rows


def latest_file(label):
    files = sorted(DATA_DIR.glob(label + "_*.csv"))
    return files[-1] if files else None


def mean(rows, key):
    vals = [float(r[key]) for r in rows]
    return statistics.mean(vals) if vals else float("nan")


def std(rows, key):
    vals = [float(r[key]) for r in rows]
    return statistics.pstdev(vals) if len(vals) > 1 else float("nan")


def load_latest_group():
    data = {}
    missing = []
    for label in STATIC_POSES + ROTATION_POSES + HEADING_POSES:
        path = latest_file(label)
        if path is None:
            missing.append(label)
        else:
            rows = read_csv(path)
            data[label] = {"path": path, "rows": rows}
    return data, missing


def wrap_deg(x):
    while x >= 180.0:
        x -= 360.0
    while x < -180.0:
        x += 360.0
    return x


def heading_from_mag(mx, my):
    return math.degrees(math.atan2(-my, mx))


def vector_norm(x, y, z):
    return math.sqrt(x * x + y * y + z * z)


def analyze_static(data):
    rows = []
    expected = {
        "static_pos_x_up": ("ax_g", +1.0),
        "static_neg_x_up": ("ax_g", -1.0),
        "static_pos_y_up": ("ay_g", +1.0),
        "static_neg_y_up": ("ay_g", -1.0),
        "static_pos_z_up": ("az_g", +1.0),
        "static_neg_z_up": ("az_g", -1.0),
    }
    ok = True
    for label, (axis, sign) in expected.items():
        item = data[label]
        r = item["rows"]
        ax = mean(r, "ax_g")
        ay = mean(r, "ay_g")
        az = mean(r, "az_g")
        vals = {"ax_g": ax, "ay_g": ay, "az_g": az}
        dominant_axis = max(vals, key=lambda k: abs(vals[k]))
        dominant_value = vals[dominant_axis]
        expected_ok = dominant_axis == axis and dominant_value * sign > 0.75
        norm_g = vector_norm(ax, ay, az)
        if not expected_ok:
            ok = False
        rows.append({
            "test": label,
            "type": "static_accel",
            "expected": "%s %.0f" % (axis, sign),
            "observed": "%s %.6f" % (dominant_axis, dominant_value),
            "mean_ax": ax,
            "mean_ay": ay,
            "mean_az": az,
            "norm": norm_g,
            "status": "PASS" if expected_ok else "CHECK",
        })
    return ok, rows


def analyze_rotation(data):
    rows = []
    expected = {
        "rotate_positive_roll_x": "gx_dps",
        "rotate_positive_pitch_y": "gy_dps",
        "rotate_positive_yaw_z": "gz_dps",
    }
    ok = True
    for label, axis in expected.items():
        r = data[label]["rows"]
        stds = {
            "gx_dps": std(r, "gx_dps"),
            "gy_dps": std(r, "gy_dps"),
            "gz_dps": std(r, "gz_dps"),
        }
        dominant_axis = max(stds, key=stds.get)
        expected_ok = dominant_axis == axis
        if not expected_ok:
            ok = False
        rows.append({
            "test": label,
            "type": "gyro_rotation",
            "expected": axis,
            "observed": "%s std=%.6f" % (dominant_axis, stds[dominant_axis]),
            "std_gx": stds["gx_dps"],
            "std_gy": stds["gy_dps"],
            "std_gz": stds["gz_dps"],
            "status": "PASS" if expected_ok else "CHECK",
        })
    return ok, rows


def analyze_heading(data):
    rows = []
    headings = {}
    for label in HEADING_POSES:
        r = data[label]["rows"]
        mx = mean(r, "mx_raw")
        my = mean(r, "my_raw")
        mz = mean(r, "mz_raw")
        h = heading_from_mag(mx, my)
        headings[label] = h
        rows.append({
            "test": label,
            "type": "mag_heading",
            "expected": "fixed external direction",
            "observed": "heading %.3f deg" % h,
            "mean_mx": mx,
            "mean_my": my,
            "mean_mz": mz,
            "status": "INFO",
        })

    # If each body axis points to the same external direction, the magnetic
    # vector in body frame should rotate by about 90 degrees per step.
    diffs = [
        wrap_deg(headings["heading_y_forward"] - headings["heading_x_forward"]),
        wrap_deg(headings["heading_neg_x_forward"] - headings["heading_y_forward"]),
        wrap_deg(headings["heading_neg_y_forward"] - headings["heading_neg_x_forward"]),
    ]
    abs_ok = all(60.0 <= abs(d) <= 120.0 for d in diffs)
    rows.append({
        "test": "mag_horizontal_90deg_sequence",
        "type": "mag_heading_check",
        "expected": "about 90 deg steps",
        "observed": "; ".join("%.3f" % d for d in diffs),
        "status": "PASS" if abs_ok else "CHECK",
    })
    return abs_ok, rows


def write_summary(rows):
    keys = sorted({k for row in rows for k in row.keys()})
    with OUT_SUMMARY.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=keys)
        writer.writeheader()
        writer.writerows(rows)


def write_report(rows, static_ok, rotation_ok, heading_ok, missing):
    lines = []
    lines.append("# Axis Mapping Verification Report")
    lines.append("")
    if missing:
        lines.append("Missing tests: " + ", ".join(missing))
        lines.append("")
    lines.append("## Overall Result")
    lines.append("")
    lines.append("- IMU accelerometer axis check: " + ("PASS" if static_ok else "CHECK"))
    lines.append("- Gyroscope dominant rotation axis check: " + ("PASS" if rotation_ok else "CHECK"))
    lines.append("- Magnetometer horizontal heading sequence check: " + ("PASS" if heading_ok else "CHECK"))
    lines.append("")
    lines.append("Recommended body-frame mapping when all checks pass:")
    lines.append("")
    lines.append("```python")
    lines.append("def imu_to_body(ax, ay, az, gx, gy, gz):")
    lines.append("    return ax, ay, az, gx, gy, gz")
    lines.append("")
    lines.append("def mag_to_body(mx, my, mz):")
    lines.append("    return mx, my, mz")
    lines.append("```")
    lines.append("")
    lines.append("If the magnetometer heading check is CHECK, keep IMU mapping unchanged and adjust only `mag_to_body()`.")
    lines.append("")
    lines.append("## Detailed Checks")
    lines.append("")
    for row in rows:
        lines.append("- %s [%s]: %s, observed %s" % (
            row.get("test", ""),
            row.get("status", ""),
            row.get("expected", ""),
            row.get("observed", ""),
        ))
    OUT_REPORT.parent.mkdir(parents=True, exist_ok=True)
    OUT_REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    data, missing = load_latest_group()
    if missing:
        print("Missing test CSV files:")
        for label in missing:
            print(" -", label)
        print("Run pc_axis_mapping_verify.py first.")
        return

    static_ok, static_rows = analyze_static(data)
    rotation_ok, rotation_rows = analyze_rotation(data)
    heading_ok, heading_rows = analyze_heading(data)
    all_rows = static_rows + rotation_rows + heading_rows
    write_summary(all_rows)
    write_report(all_rows, static_ok, rotation_ok, heading_ok, missing)

    print("Wrote:", OUT_SUMMARY)
    print("Wrote:", OUT_REPORT)
    print("IMU static:", "PASS" if static_ok else "CHECK")
    print("Gyro rotation:", "PASS" if rotation_ok else "CHECK")
    print("Mag heading:", "PASS" if heading_ok else "CHECK")


if __name__ == "__main__":
    main()
